export enum MemberInformation {
    GET_MEMBER_INFORMATION_START = "GET_MEMBER_INFORMATION_START",
    GET_MEMBER_INFORMATION_SUCCESS = "GET_MEMBER_INFORMATION_SUCCESS",
    GET_MEMBER_INFORMATION_FAIL = "GET_MEMBER_INFORMATION_FAIL"
}