export enum PaymentInformation {
    GET_PAYMENT_INFORMATION_START = "GET_PAYMENT_INFORMATION_START",
    GET_PAYMENT_INFORMATION_SUCCESS = "GET_PAYMENT_INFORMATION_SUCCESS",
    GET_PAYMENT_INFORMATION_FAIL = "GET_PAYMENT_INFORMATION_FAIL",
  }
  